### PR TITLE
Allow users to disable or customize checks.

### PR DESCRIPTION
**Pull request by jmcarp**
* Allow any check to be disabled
* Expose configuration options for some checks that could use them

cc @cnelson @jcscottiii

### CODE REVIEW

**Comment by jmcarp** [comment]
WDYT @cppforlife ?

**Comment by cppforlife** [comment]
@jmcarp slept on it. im going to pull this in within next few days.

**Comment by jmcarp** [comment]
@cppforlife: let me know if this needs revisions.

**Comment by cnelson** [comment]
Any chance we could see this merged this week?

**Comment by cppforlife** [comment]
@jmcarp oops deleted one of your comments accidentally... jumpy browser scrolling.

@cnelson pulling in now...

**Pull request merged**
